"""Add UserAPIKey model

Revision ID: bc03aab4ddd7
Revises: 002_auth
Create Date: 2026-06-27 15:10:03.004717
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'bc03aab4ddd7'
down_revision: Union[str, None] = '002_auth'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('encrypted_key', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_api_keys_user_id'), 'user_api_keys', ['user_id'], unique=False)
    op.alter_column('api_keys', 'scans_used',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('api_keys', 'scans_limit',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)
    op.drop_index('ix_api_keys_key_hash', table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scans', 'risk_score',
               existing_type=sa.FLOAT(),
               server_default=None,
               nullable=False)
    op.alter_column('scans', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=False)
    op.alter_column('scans', 'source_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=False)
    op.alter_column('scans', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('scans', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)
    op.drop_index('ix_scans_created_at', table_name='scans')
    op.drop_index('ix_scans_scan_id', table_name='scans')
    op.create_index(op.f('ix_scans_scan_id'), 'scans', ['scan_id'], unique=True)
    op.alter_column('threat_patterns', 'times_detected',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('threat_patterns', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('threat_patterns', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('users', 'plan',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'scan_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'true'"),
               existing_nullable=False)
    op.alter_column('users', 'scan_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('users', 'plan',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'''free'''"),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('threat_patterns', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=True)
    op.alter_column('threat_patterns', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'true'"),
               nullable=True)
    op.alter_column('threat_patterns', 'times_detected',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               nullable=True)
    op.drop_index(op.f('ix_scans_scan_id'), table_name='scans')
    op.create_index('ix_scans_scan_id', 'scans', ['scan_id'], unique=False)
    op.create_index('ix_scans_created_at', 'scans', ['created_at'], unique=False)
    op.alter_column('scans', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=True)
    op.alter_column('scans', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'true'"),
               nullable=True)
    op.alter_column('scans', 'source_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'''upload'''"),
               nullable=True)
    op.alter_column('scans', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'''clean'''"),
               nullable=True)
    op.alter_column('scans', 'risk_score',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0.0'"),
               nullable=True)
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'false'"),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index('ix_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=True)
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'true'"),
               nullable=True)
    op.alter_column('api_keys', 'scans_limit',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'500'"),
               nullable=True)
    op.alter_column('api_keys', 'scans_used',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               nullable=True)
    op.drop_index(op.f('ix_user_api_keys_user_id'), table_name='user_api_keys')
    op.drop_table('user_api_keys')
    # ### end Alembic commands ###
