"""Add threat intel tables

Revision ID: c69b92c1809b
Revises: bc03aab4ddd7
Create Date: 2026-06-27 15:38:48.630639
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c69b92c1809b'
down_revision: Union[str, None] = 'bc03aab4ddd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('affected_tech', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cve_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cve_records_cve_id'), ['cve_id'], unique=True)

    op.create_table('ioc_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('reporter_id', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ioc_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ioc_records_file_hash'), ['file_hash'], unique=True)

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.alter_column('scans_used',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
        batch_op.alter_column('scans_limit',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)
        batch_op.drop_index('ix_api_keys_key_hash')
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('is_revoked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.alter_column('risk_score',
               existing_type=sa.FLOAT(),
               server_default=None,
               nullable=False)
        batch_op.alter_column('risk_level',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=False)
        batch_op.alter_column('source_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=False)
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)
        pass  # Bypassed ghost index drop
        batch_op.drop_index('ix_scans_scan_id')
        batch_op.create_index(batch_op.f('ix_scans_scan_id'), ['scan_id'], unique=True)

    with op.batch_alter_table('threat_patterns', schema=None) as batch_op:
        batch_op.alter_column('times_detected',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)

    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('plan',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('scan_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_index('ix_users_email')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index('ix_users_username', ['username'], unique=False)
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('ix_users_email', ['email'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'true'"),
               existing_nullable=False)
        batch_op.alter_column('scan_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('plan',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'''free'''"),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('threat_patterns', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'true'"),
               nullable=True)
        batch_op.alter_column('times_detected',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               nullable=True)

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_scan_id'))
        batch_op.create_index('ix_scans_scan_id', ['scan_id'], unique=False)
        batch_op.create_index('ix_scans_created_at', ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=True)
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'true'"),
               nullable=True)
        batch_op.alter_column('source_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'''upload'''"),
               nullable=True)
        batch_op.alter_column('risk_level',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'''clean'''"),
               nullable=True)
        batch_op.alter_column('risk_score',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0.0'"),
               nullable=True)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('is_revoked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'false'"),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.create_index('ix_api_keys_key_hash', ['key_hash'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'true'"),
               nullable=True)
        batch_op.alter_column('scans_limit',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'500'"),
               nullable=True)
        batch_op.alter_column('scans_used',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               nullable=True)

    with op.batch_alter_table('ioc_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ioc_records_file_hash'))

    op.drop_table('ioc_records')
    with op.batch_alter_table('cve_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cve_records_cve_id'))

    op.drop_table('cve_records')
    # ### end Alembic commands ###
